### ISSUE TITLE
未找到命令

### ISSUE THREAD

**Issue by rancongjie** [WangYihang/GitHacker#11]
![image](https://user-images.githubusercontent.com/13307672/118389643-5e957900-b65d-11eb-8777-3103ca9b6c3d.png)

**Comment by rancongjie** [comment]
centos 7.7

**Comment by WangYihang** [comment]
收到，我待会儿测试一下。

**Comment by WangYihang** [comment]
这边在 Docker 里测试没问题的。

#### 启动 Docker

```bash
docker run -it centos /bin/bash
```

#### 安装

```bash
yum install git python3
pip3 install GitHacker
```

#### 运行

```
githacker --help
```

**Comment by WangYihang** [comment]
你可以尝试使用 `locate githacker` 来找一下已安装的可执行文件的位置，然后临时使用绝对路径运行。

**Comment by WangYihang** [comment]
另外，我也在你说的 CentOS 7 （`docker run -it centos:7.7.1908 /bin/bash`）的 Docker 中进行了测试，结果相同，正常。

**Comment by rancongjie** [comment]
![image](https://user-images.githubusercontent.com/13307672/118398651-1d688d80-b68c-11eb-9c0c-0fb97e58a779.png)
不知为何 安到这了

**Comment by rancongjie** [comment]
可能我环境问题，谢谢

**Comment by WangYihang** [comment]
> 可能我环境问题，谢谢

可以尝试将整个路径加入到 `$PATH` 里
