### ISSUE TITLE
Disable SSLCertVerification?

### ISSUE THREAD

**Issue by corsch** [WangYihang/GitHacker#16]
I get an SSLError ("hostname '<IP>' doen't match '<FQDN') when connecting to repository.
I'm aware that the certificate is wrong, but unfortunately I cannot connect via FQDN.

Is there a switch to disable the certificate verification in GitHacker?

**Comment by WangYihang** [comment]
Thanks for reporting, I will fix it soon by default disable SSL verification. The fix will be released in the next release.

**Comment by corsch** [comment]
Thank you very much :)

**Comment by WangYihang** [comment]
v1.0.9 released.

**Comment by corsch** [comment]
Unfortunately the new version has an issue :(

"AttributeError:'GitHacker' object has no attribute 'verify'

**Comment by WangYihang** [comment]
oh, it's my fault. Wait a minute.

**Comment by WangYihang** [comment]
```
pip3 install -i https://pypi.org/simple/ githacker==1.0.10
```
It seems fine now, check it out~
Thanks for reporting!

**Comment by corsch** [comment]
Thank you for the new release :)

I'm able to connect now!
