### ISSUE TITLE
python: can't open file 'GitHacker.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by kisspanda** [WangYihang/GitHacker#17]
![1](https://user-images.githubusercontent.com/37388439/127600083-d68abfca-58a1-4e00-800b-7d9da468e780.png)

试了好多遍，后来直接git clone之后，pip了环境，删了文件夹又重来了一边
还是提示找不到py文件。。。。

一脸懵

**Comment by kisspanda** [comment]
window cmd下我也试了，结果一样。。。。。

继续一脸懵

**Comment by WangYihang** [comment]
![image](https://user-images.githubusercontent.com/16917636/127609278-2932df72-cc07-491f-a581-0d7a58e18f47.png)
