### ISSUE TITLE
git log -relog 版本不全

### ISSUE THREAD

**Issue by wuxiaoyang-233** [WangYihang/GitHacker#24]
![图片](https://user-images.githubusercontent.com/65070121/179460703-cea0bb21-fe8f-4a68-8c07-77492ba692f5.png)

原本应该有历史版本的，但是只出现一个版本
![图片](https://user-images.githubusercontent.com/65070121/179460978-84596505-cf52-4011-a7cf-553dbf4d0e6d.png)

**Comment by WangYihang** [comment]
感谢反馈，我有空了研究一下子。

**Comment by wuxiaoyang-233** [comment]
太感谢了，辛苦啦。我是在做一道ctf题发现做不了，有在怀疑是不是题目环境有问题，在buuctf里 [网鼎杯 2018] Comment 那一题，试了很多次不行…发自我的手机-------- 原始邮件 --------发件人： WangYihang ***@***.***>日期： 2022年7月18日周一 下午3:35收件人： WangYihang/GitHacker ***@***.***>抄送： Oasis_wu ***@***.***>, Author ***@***.***>主    题： Re: [WangYihang/GitHacker] git log -relog 版本不全 (Issue #24)

感谢反馈，我有空了研究一下子。

**Comment by WangYihang** [comment]
Duplicate with #23

**Comment by WangYihang** [comment]
Fixed. 

See: https://github.com/WangYihang/GitHacker/issues/23#issuecomment-1195241508

**Comment by WangYihang** [comment]
> 太感谢了，辛苦啦。我是在做一道ctf题发现做不了，有在怀疑是不是题目环境有问题，在buuctf里 [网鼎杯 2018] Comment 那一题，试了很多次不行…

已解决，麻烦师傅看一下这个 #23 的评论区  https://github.com/WangYihang/GitHacker/issues/23#issuecomment-1195241508 。

**Comment by wuxiaoyang-233** [comment]
感谢！
