### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by d0gman** [WangYihang/GitHacker#3]
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "GitHacker.py", line 187, in <module>
    main()
  File "GitHacker.py", line 159, in main
    master = open("./%s/.git/logs/refs/heads/master" % temppath, "r")
IOError: [Errno 2] No such file or directory: './www_xx_com_/.git/logs/refs/heads/master'

**Comment by d0gman** [comment]
what can i do

**Comment by WangYihang** [comment]
Make sure the following things:
1. Windows is not supported.
2. You need to clone this repo instead of downloading the zip file.
```
git clone https://github.com/WangYihang/GitHacker.git 
```
