### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by w2n1ck** [WangYihang/GitHacker#6]
![image](https://user-images.githubusercontent.com/26704158/70032376-54f28f80-15e8-11ea-8799-2db2e545cc89.png)

**Comment by WangYihang** [comment]
请使用 git clone 的方式下载工具，而不是直接下载 zip 包

**Comment by peri0d** [comment]
> 
> 
> 请使用 git clone 的方式下载工具，而不是直接下载 zip 包

git clone 也是这种情况

**Comment by WangYihang** [comment]
@peri0d 稍等，我这边测试一下。

**Comment by WangYihang** [comment]
@peri0d 我这边没问题的呀... 您那边可以提供一下操作系统/Python版本等信息吗？
我这边测试的环境是：
```
$ cat /etc/issue
Ubuntu 18.04.4 LTS \n \l

$ python --version                          
Python 3.6.9
```
![image](https://user-images.githubusercontent.com/16917636/75619634-88c65c80-5bb9-11ea-8926-7fe4b075a4f3.png)
![image](https://user-images.githubusercontent.com/16917636/75619650-b1e6ed00-5bb9-11ea-8db6-b2a22df97bd2.png)

**Comment by peri0d** [comment]
可能是靶机的问题，我重启了一下靶机就好了，同一个环境



---Original---

**Comment by WangYihang** [comment]
好的，问题已经解决的话，那该 issue 将会关闭。感谢~
