### ISSUE TITLE
error after success message

### ISSUE THREAD

**Issue by MR-pentestGuy** [WangYihang/GitHacker#8]
Traceback (most recent call last):
  File "GitHacker.py", line 186, in <module>
    main()
  File "GitHacker.py", line 162, in main
    nexthash = line.split(" ")[1]
IndexError: list index out of range

**Comment by WangYihang** [comment]
Thanks for reporting! For reproducing, could you please provide the target website you were testing?

**Comment by sri-sanath** [comment]
affiliate.canva.com

**Comment by N0b1ta** [comment]
> Traceback (most recent call last):
> File "GitHacker.py", line 186, in
> main()
> File "GitHacker.py", line 162, in main
> nexthash = line.split(" ")[1]
> IndexError: list index out of range

try use on linux XD

**Comment by WangYihang** [comment]
@N0b1ta could you please provide the target website you were testing?

**Comment by WangYihang** [comment]
Also, please provide the environment you are using, eg: git version

**Comment by KangbaoShi** [comment]
uname
Linux VM-0-9-ubuntu 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Traceback (most recent call last):
  File "GitHacker.py", line 195, in <module>
    main()
  File "GitHacker.py", line 171, in main
    nexthash = line.split(" ")[1]
IndexError: list index out of range

ctf buuoj
https://buuoj.cn/challenges#[BJDCTF2020]Mark%20loves%20cat

**Comment by WangYihang** [comment]
@KangbaoShi @N0b1ta @MR-pentestGuy 
Solved. Please check it out.
Thank you guys for reporting this issue.

**Comment by WangYihang** [comment]
You can use use the following command to install GitHacker
```bash
pip3 install -i https://pypi.org/simple/ GitHacker
```
Then, run it like this.
```bash
githacker --url 'http://fa72366b-2c18-4235-9211-77c0ee296da0.node3.buuoj.cn/' --folder buuoj --threads 1
```

#### Demo
![demo](https://user-images.githubusercontent.com/16917636/117931033-42c66600-b331-11eb-92e7-d375ab5c62fd.gif)

**Comment by KangbaoShi** [comment]
一楼应该和我一样。使用的是源码编译。所以报错了。

**Comment by WangYihang** [comment]
> 一楼应该和我一样。使用的是源码编译。所以报错了。

你们的做法没问题，之前确实是有 bug 没有处理到位。@KangBaoShi
现在重构了代码，不会出现之前的问题了，另外现在也支持使用 pip 安装了。
如果方便的话，麻烦你帮忙测试一下之前的问题是否还存在，感谢！

**Comment by KangbaoShi** [comment]
可以了。但必须以root用户编译。不然加入环境变量的时候会出现警告。无法加入到环境变量中。
WARNING: The script githacker is installed in '/home/xxx/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

**Comment by WangYihang** [comment]
> 可以了。但必须以root用户编译。不然加入环境变量的时候会出现警告。无法加入到环境变量中。
> WARNING: The script githacker is installed in '/home/xxx/.local/bin' which is not on PATH.
> Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

好的，既然问题已经解决，本 Issue 关闭。
